
CREATE TABLE IF NOT EXISTS borger (
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
   	[UserId] INTEGER NOT NULL,
	[CreatedAt] DATETIME NOT NULL);


CREATE TABLE IF NOT EXISTS address (
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
   	[BorgerUserId] INTEGER NOT NULL,
	[Address] VARCHAR NOT NULL,
	[CreatedAt] DATETIME NOT NULL,
	[IsValid] INTEGER DEFAULT 1,
	FOREIGN KEY ([BorgerUserId]) REFERENCES [borger]([Id]));